### ISSUE TITLE
Idea : Practice & Normal Progress Bar Colors

### ISSUE THREAD

**Issue by RikuNova** [AnhNguyenlost13/progress-bar-thingy#13]
An Idea I have for the mod is for a setting to make the progress bar to be Normal/Practice Mode reliant. To put it simply, if this setting is toggled, the progress bar will be green in normal mode, but will change to light blue in practice mode. (The same colors as seen in the progress bars in the level menu/pause screen.)

**Comment by AnhNguyenlost13** [comment]
Finally implemented!
